apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rcon-web-admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rcon-web-admin.labels" . | nindent 4 }}
