# Default values for rcon-web-admin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/itzg/rcon
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This will expose 2 different services - http and websockets
# If you want to know why it's separate - ask developer of original project
# because I have no clue
service:
  # Supported options: Ingress + ClusterIP or LoadBalancer
  type: ClusterIP
  httpPort: 80
  wsPort: 4327

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: chart-example.local
  path: /
  pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

rconWeb:
  # Sets the initial user as an admin
  isAdmin: false
  # Sets the initial user's username
  username: admin
  # Sets the initial user's password
  password: ""
  # Name of existing secret with UI password
  passwordExistingSecret:
  passwordKey: "password"
  # The initial game you wish to control (minecraft / rust / csgo / other)
  game: minecraft
  # The display name of the initial server (if unset; defaults to value of RWA_GAME)
  serverName: minecraft
  # The initial RCON server to control
  rconHost: 127.0.0.1
  # The port number of the initial RCON server to control
  rconPort: 25575
  # The password for the initial RCON server to control
  rconPassword: ""
  # Name of existing secret with RCON password
  rconPasswordExistingSecret:
  rconPasswordKey: "rcon-password"
  # Prevent the initial user user executing these commands
  restrictCommands: []
  # Hide this list of widgets from the initial user
  restrictWidgets: []
  # Prevent the initial user changing options in the widget options tab
  immutableWidgetOptions: false
  # Enables 'web rcon' if supported by the game server
  websocketRcon: false
