apiVersion: v1
kind: Service
metadata:
  name: {{ template "bungee.fullname" . }}
  labels:
    app: {{ template "bungee.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.serviceAnnotations | indent 4 }}
spec:
{{- if (or (eq .Values.bungeeCord.serviceType "ClusterIP") (empty .Values.bungeeCord.serviceType)) }}
  type: ClusterIP
{{- else if eq .Values.bungeeCord.serviceType "LoadBalancer" }}
  type: {{ .Values.bungeeCord.serviceType }}
  {{- if .Values.bungeeCord.loadBalancerIP }}
  loadBalancerIP: {{ .Values.bungeeCord.loadBalancerIP }}
  {{- end }}
  {{- if .Values.bungeeCord.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.bungeeCord.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.bungeeCord.serviceType }}
{{- end }}
  {{- if .Values.bungeeCord.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.bungeeCord.externalTrafficPolicy }}
  {{- end }}
  ports:
  - name: bungee
    port: 25565
    targetPort: bungee
    {{- if .Values.bungeeCord.nodePort }}
    nodePort: {{ .Values.bungeeCord.nodePort }}
    {{- end }}
    protocol: TCP
  selector:
    app: {{ template "bungee.fullname" . }}
  {{- if .Values.bungeeCord.externalIPs }}
  externalIPs:
    {{- with .Values.bungeeCord.externalIPs }}
      {{- range . }}
        - {{ . | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
