{{- if .Values.bungeeCord.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bungee.fullname" . }}-config
  labels:
    app: {{ template "bungee.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yml: |
{{ toYaml .Values.bungeeCord.config | indent 4 }}
{{- end }}
