apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bungee.fullname" . }}
  labels:
    app: {{ template "bungee.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  rcon-password: {{ default "" .Values.bungeeCord.rcon.password | b64enc | quote }}
