{{- if not .Values.minecraftProxy.rcon.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "proxy.fullname" . }}-rcon"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "proxy.fullname" . }}
    chart: "{{ include "chart.fullname" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  rcon-password:
    {{ default "" .Values.minecraftProxy.rcon.password | b64enc | quote }}
{{- end }}