{{- if .Values.minecraftProxy.velocityForwardingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "proxy.fullname" . }}-velocity-forwarding-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "proxy.fullname" . }}
    chart: "{{ include "chart.fullname" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  velocity-forwarding-secret:
    {{ default "" .Values.minecraftProxy.velocityForwardingSecret | b64enc | quote }}
{{- end }}
