# This must be overridden, since we can't accept this for the user.
minecraftServer:
  eula: "TRUE"
# fix in place and rebased
extraVolumes:
  - name: test
    emptyDir: {}
initContainers:
  - name: test
    image: busybox
    command:
      - touch
    args:
      - /test/hello
    volumeMounts:
      - name: test
        mountPath: /test
