{{- if default "" .Values.minecraftServer.dynmap.ingress.enabled }}
{{- $minecraftFullname := include "minecraft.fullname" . }}
{{- $serviceName := printf "%s-dynmap" $minecraftFullname }}
{{- $servicePort := .Values.minecraftServer.dynmap.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $minecraftFullname }}-dynmap"
  {{- if .Values.minecraftServer.dynmap.ingress.annotations }}
  annotations:
    {{- toYaml .Values.minecraftServer.dynmap.ingress.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: "{{ $minecraftFullname }}-dynmap"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
{{- if .Values.minecraftServer.dynmap.ingress.tls }}
  tls:
  {{- range .Values.minecraftServer.dynmap.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.minecraftServer.dynmap.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: {{ .path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ $serviceName }}
            port:
              number: {{ $servicePort }}
  {{- end }}
{{- end }}
