{{- if not .Values.minecraftServer.rcon.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "minecraft.fullname" . }}-rcon"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "minecraft.fullname" . }}
    chart: {{ template "chart.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: {{ template "minecraft.fullname" . }}
    app.kubernetes.io/version: {{ template "chart.version" . }}
type: Opaque
data:
  rcon-password: {{ default "" .Values.minecraftServer.rcon.password | b64enc | quote }}
{{- end }}
{{- if not .Values.minecraftServer.autoCurseForge.apiKey.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "minecraft.fullname" . }}-curseforge"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "minecraft.fullname" . }}
    chart: {{ template "chart.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: {{ template "minecraft.fullname" . }}
    app.kubernetes.io/version: {{ template "chart.version" . }}
type: Opaque
data:
  cf-api-key: {{ default "" .Values.minecraftServer.autoCurseForge.apiKey.key | b64enc | quote }}
{{- end }}
