{{- if eq .Values.minecraftRouter.autoScale.configObject "ConfigMap" | and .Values.minecraftRouter.autoScale.allowDeny }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mc-router.fullname" . }}-autoscale-allow-deny
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mc-router.labels" . | nindent 4 }}
data:
  auto-scale-allow-deny-list.json: {{ .Values.minecraftRouter.autoScale.allowDeny | toJson | squote }}
{{- end }}
