apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mc-router.fullname" . }}
  labels:
    {{- include "mc-router.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["watch","list"]
  {{- if .Values.minecraftRouter.autoScaleUp.enabled }}
  - apiGroups: ["apps"]
    resources: ["statefulsets", "statefulsets/scale"]
    verbs: ["watch","list","get","update"]
  {{- end }}
