apiVersion: v1
kind: Service
metadata:
  name: {{ include "mc-router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mc-router.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.services.minecraft.annotations | nindent 4 }}
spec:
  {{- with .Values.services.minecraft }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      {{- if list "LoadBalancer" "NodePort" | has .type }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      {{- end }}
      targetPort: minecraft
      protocol: TCP
      name: minecraft
  {{- end }}
  selector:
    {{- include "mc-router.selectorLabels" . | nindent 4 }}
  {{- if .Values.services.extraServiceSpec }}
  {{ toYaml .Values.services.extraServiceSpec | nindent 2 }}
  {{- end }}
