{{- if .Values.minecraftRouter.autoScale.allowDeny }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mc-router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mc-router.labels" . | nindent 4 }}
data:
  auto-scale-allow-deny-list.json: {{ .Values.minecraftRouter.autoScale.allowDeny | toJson | b64enc }}
{{- end }}
