apiVersion: v1
kind: Service
metadata:
  name: {{ include "mc-router.fullname" . }}
  labels:
    {{- include "mc-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.minecraftPort }}
      targetPort: minecraft
      protocol: TCP
      name: minecraft
  selector:
    {{- include "mc-router.selectorLabels" . | nindent 4 }}
