name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history to get commit logs

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Dependencies
        run: |
          # Install Helm
          curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          # Install git-chglog
          sudo apt-get update && sudo apt-get install -y git-chglog

      - name: Generate per-chart CHANGELOG.md files
        run: |
          CHARTS_CHANGED=$(git diff --dirstat=files,0 HEAD~1 HEAD | cut -f2 | grep -E '^charts/' | cut -d'/' -f2 | sort | uniq)
          for chart in $CHARTS_CHANGED; do
            echo "Generating changelog for chart: $chart"
            # Navigate to the chart directory
            cd charts/$chart
            # Generate the changelog for the chart
            git-chglog --path . > CHANGELOG.md
            cd ../../
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_repo_url: https://itzg.github.io/minecraft-server-charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
