name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Turnstyle
        uses: softprops/turnstyle@v2
        with:
          continue-after-seconds: 180
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add dependency chart repos
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo update stable

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      ## https://github.com/helm/chart-releaser-action/issues/107#issuecomment-2133797963
      - name: Push Charts to GHCR
        run: |
          for pkg in .cr-release-packages/*; do
            if [ -z "${pkg:-}" ]; then
              break
            fi

            chart_filename=$(basename "$pkg" .tgz)
            chart_name=$(echo "$chart_filename" | sed -E 's/-[0-9]+\.[0-9]+\.[0-9]+$//')
            chart_version=$(echo "$chart_filename" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+$')

            push_output=$(helm push "${pkg}" oci://ghcr.io/${{ github.repository }}/charts 2>&1)
            
            digest=$(echo "$push_output" | grep -oE 'sha256:[a-f0-9]{64}')
            cosign sign --yes "oci://ghcr.io/${{ github.repository }}/charts/$chart_name@$digest"
          done
